spring:
    profiles: 
        active: local
    output:
      ansi:
        enabled: never
        
---
spring:
    profiles: local 

    #Hikari
    datasource:
        hikari:
           driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
           jdbc-url: jdbc:log4jdbc:mysql://stg-puppyou-app.cqyxmk2lesk3.ap-northeast-2.rds.amazonaws.com:13306/puppyou?serverTimezone=Asia/Seoul&sslMode=DISABLED           username: admin
           password: shs1q2w3e4r! 
           maximum-pool-size: 10
           data-source-properties: 
            cachePrepStmts: true 
            prepStmtCacheSize: 250 
            prepStmtCacheSqlLimit: 2048 
            useServerPrepStmts: true
           connection-test-query: SELECT 1
server:
    port: 6000
    servlet:
        session:
            timeout: 10m
            cookie:
                name: SESSION_PPY
                
#logging
logging:
  level:
    root: info
    '[org.springframework.web]': debug
#    sql: error
    jdbc: off
    jdbc.sqltiming: info
 
#resttemplate
#rest:
#    puppyou:

#admin Token
admin:
  token: 0f63ed073181c8f659ccc294a24fe8abd1620ccc77db308c88af64d69374bd3a  
  
#push url
PUSH:
  URL: http://localhost:8888 

---
spring:
    profiles: stg 
    #Hikari
    datasource:
        hikari:
           driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
           jdbc-url: jdbc:log4jdbc:mysql://stg-puppyou-app.cqyxmk2lesk3.ap-northeast-2.rds.amazonaws.com:13306/puppyou?serverTimezone=Asia/Seoul
           username: admin
           password: shs1q2w3e4r! 
           maximum-pool-size: 10
           data-source-properties: 
            cachePrepStmts: true 
            prepStmtCacheSize: 250 
            prepStmtCacheSqlLimit: 2048 
            useServerPrepStmts: true
#logging
logging:
  level:
    root: info
    '[org.springframework.web]': debug
#    sql: error
    jdbc: off
    jdbc.sqltiming: error

server:
    port: 6000
    servlet:
        session:
            timeout: 10m
            cookie:
                name: SESSION_PPY
#resttemplate
rest:
    puppyou:             
#seyfert value
domain:
  uri: https://stg-puppyou.co.kr

#admin Token
admin:
  token: 0f63ed073181c8f659ccc294a24fe8abd1620ccc77db308c88af64d69374bd3a 
  
  
#push url
PUSH:
  URL: http://internal-STG-PUPPYOU-PUSH-ALB-208249258.ap-northeast-2.elb.amazonaws.com
  
#############################################################################################################
---
spring:
    profiles: prod 
    #Hikari
    datasource:
        hikari:
           driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
           jdbc-url: jdbc:log4jdbc:mysql://prod-mysql-puppyou-app.cqyxmk2lesk3.ap-northeast-2.rds.amazonaws.com:13306/puppyou?serverTimezone=Asia/Seoul&sslMode=DISABLED
           username: admin
           password: shs1q2w3e4r! 
           maximum-pool-size: 10
           max-lifetime: 540000 
           leakDetectionThreshold : 535000
           connection-test-query: SELECT 1 
#logging
logging:
  level:
    root: info
    '[org.springframework.web]': error
    sql: error
    jdbc: error
    jdbc.sqlonly: error

#resttemplate
rest:
    puppyou:
        
server:
    port: 6000
    servlet:
        session:
            timeout: 10m
            cookie:
                name: SESSION_PPY

#push url
PUSH:
  URL: http://internal-PROD-PUPPYOU-PUSH-1417431903.ap-northeast-2.elb.amazonaws.com